// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/store-dashboard/CommandCenter.tsx": () => import("../components/mockups/store-dashboard/CommandCenter.tsx"),
  "./components/mockups/store-dashboard/GroupedSidebar.tsx": () => import("../components/mockups/store-dashboard/GroupedSidebar.tsx"),
  "./components/mockups/store-dashboard/NestedSegments.tsx": () => import("../components/mockups/store-dashboard/NestedSegments.tsx")
};
